name: Doxygen Deploy

# refer: https://lang-ship.com/blog/work/github-doxygen-page/

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/doxygen/html
          config_file: docs/doxygen/Doxyfile
